database:
  adapter: mysql
  database: pokerru_mail
  username: toor
  password: Awycehe2iS
  socket: /tmp/mysql.sock

log:
  level: debug
  file: ipcauthpipe.log

invision:
  tables_prefix: ibf_

mail:
  address_format: %s@poker.ru
  owner_uid: 2001
  owner_name: vmail
  owner_gid: 1000
  owner_group: virtualusers
  home_dir: /tmp/%s