database:
  adapter: mysql
  database: pokerru_mail
  username: root
  password: Awycehe2iS
  socket: /var/run/mysqld/mysqld.sock

log:
  level: debug
  file: ipcauthpipe.log

invision:
  tables_prefix: ibf_

mail:
  address_format: %s@poker.ru
  owner_uid: 2001
  owner_gid: 1000
  home_dir: /tmp/%s